name: Publish to hex.pm
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: erlang:latest

    steps:
      - uses: actions/checkout@v2.0.0

      - run: ./scripts/publish.sh
        env:
          HEX_API_KEY: ${{ secrets.HEX_KEY }}
